const SUCCESS = "SUCCESS";
const NOT_AUTHENTICATED = "NOT_AUTHENTICATED";
const NOT_FOUND_USER = "NOT_FOUND_USER";
const NOT_FOUND_CONVERSATION = "NOT_FOUND_CONVERSATION";
const NOT_FOUND_MESSAGE = "NOT_FOUND_MESSAGE";
const NOT_VALID_USERNAMES = "NOT_VALID_USERNAMES";
const NOT_VALID_CONTENT = "NOT_VALID_CONTENT";

module.exports = {
  SUCCESS,
  NOT_AUTHENTICATED,
  NOT_FOUND_USER,
  NOT_FOUND_CONVERSATION,
  NOT_FOUND_MESSAGE,
  NOT_VALID_USERNAMES,
  NOT_VALID_CONTENT,
};
